# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signups', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='last_name',
        ),
        migrations.AddField(
            model_name='signup',
            name='cell_phone',
            field=models.CharField(default='전화번호', help_text='-빼고 입력해주시기 바랍니다.', max_length=13),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='signup',
            name='name',
            field=models.CharField(default='이름', max_length=120),
            preserve_default=False,
        ),
    ]
